# Generated by Django 3.0.7 on 2020-06-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(default=None, max_length=24)),
                ('handler_id', models.CharField(max_length=8, unique=True)),
                ('unique_code', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Носитель',
                'verbose_name_plural': 'Носители',
            },
        ),
    ]
