# Generated by Django 3.0.7 on 2020-06-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codehandler',
            name='is_activated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codehandler',
            name='profile_id',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
