# Generated by Django 3.0.7 on 2020-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeBase', '0002_auto_20200618_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehandler',
            name='unique_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
