# Generated by Django 3.0.7 on 2020-06-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeBase', '0003_auto_20200618_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codehandler',
            name='handler_id',
        ),
        migrations.AlterField(
            model_name='codehandler',
            name='profile_id',
            field=models.IntegerField(max_length=24, null=True),
        ),
    ]
